name: SSH deploy


on:
  workflow_run:
    workflows:
      - "Push to production"
    types:
      - completed
jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PWD }}
            git switch production
            git reset --hard HEAD
            git pull --rebase origin production
            rm .env .env.example
            mv .env.production .env
            sed -i "s/DB_PASSWORD=/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/g" .env
            mkdir -p storage/plants
            composer install
            php artisan migrate:refresh --seed
            php artisan db:seed --class=PlantSeeder
            php artisan l5-swagger:generate
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
